[qc] Provide default adapter file for QC with Trimmomatic
This is Trimmomatics file with custom additions which are sequences
sourced from FASTQC's contaminants reference after they were found in some
real data

diff --git a/scripts/omics-qc-sample b/scripts/omics-qc-sample
--- a/scripts/omics-qc-sample
+++ b/scripts/omics-qc-sample
@@ -7,6 +7,8 @@
 #
 
 set -e
+RESOURCE_DIR=$(dirname "$0")/../share/geo-omics-scripts
+
 # shellcheck disable=SC2034
 {
 USAGE="[OPTIONS]..."
@@ -86,18 +88,20 @@ handle_options () {
 # default variable values
 ##########################
 
-# Set adapter file depending on server
+# Set adapter file depending on server (for scythe only)
 ADAPTERS_DEBIAN=/usr/share/trimmomatic/TruSeq3-PE-2.fa
 ADAPTERS_FLUX=/sw/lsa/centos7/trimmomatic/0.36/adapters/TruSeq3-PE-2.fa
 ADAPTERS_VONDAMM=/opt/packages/Trimmomatic/0.32/adapters/TruSeq3-PE-2.fa
 
-set_default_adapters () {
+set_default_scythe_adapters () {
     while [ $# -gt 0 ] && [ ! -r "$1" ]; do
         shift
     done
-    ADAPTERS=$1
+    ADAPTERS_SCYTHE=$1
 }
-set_default_adapters $ADAPTERS_DEBIAN $ADAPTERS_FLUX $ADAPTERS_VONDAMM
+set_default_scythe_adapters $ADAPTERS_DEBIAN $ADAPTERS_FLUX $ADAPTERS_VONDAMM
+
+ADAPTERS_TRIMMOMATIC=$RESOURCE_DIR/TruSeq3-PE-2+omics.fa
 
 # default input files as produced by prep script
 FWD_FASTQ=fwd.fastq
@@ -118,7 +122,7 @@ CPUS=2
 
 # shellcheck source=../lib/liba.sh
 # shellcheck disable=SC1091
-. "$(dirname "$0")/../share/geo-omics-scripts/liba.sh" || (echo "Failed to source script library"; exit 1)
+. "$RESOURCE_DIR/liba.sh" || (echo "Failed to source script library"; exit 1)
 
 info1 () { info "[$(basename "$PWD")] $1" ; }
 warning1 () { warning "[$(basename "$PWD")] $1" ; }
@@ -127,6 +131,14 @@ abort1 () { abort "[$(basename "$PWD")] $1" ; }
 
 # mangle verbosity args
 [[ -v V ]] && if [[ -n "$V" ]]; then V=("$V"); else V=(); fi
+
+if [[ ! -v ADAPTERS ]]; then
+    if $TRIMMOMATIC; then
+        ADAPTERS=$ADAPTERS_TRIMMOMATIC
+    else
+        ADAPTERS=$ADAPTERS_SCYTHE
+    fi
+fi
 
 # handle non-option parameters
 if [ "$#" -gt 0 ]; then
