[asm] Add normalization step with BBNorm

diff --git a/scripts/omics-assemble b/scripts/omics-assemble
--- a/scripts/omics-assemble
+++ b/scripts/omics-assemble
@@ -22,6 +22,9 @@ ARG_HELP="
                           How many CPUs/threads to use
       --force             Overwrite existing files, default is to abort when output files exist already
       --idba-ud           Use the IDBA_UD assembler instead of the default MEGAHIT
+      --normalized-reads FILE
+                          Specify an existing normalized input file to be used for the assembly.
+                          This will skip the normalization step and ignore any other input.
       --maxk N            min k parameter, must be odd with --megahit
       --mink N            max k parameter, must be odd with --megahit
       --step N            k steps parameter, must be even with --megahit
@@ -34,15 +37,27 @@ ARG_HELP="
       --reads FILE        Name of interleaved reads file, relative to each sample directory,
                           by default this is 'int.good.fasta'
       --skip-blast        Skip classification steps, by default run blast
+      --skip-normalization
+                          Do not run BBNorm to normalize read depth before assembly
       --skip-phylosift    Skip PhyloSift run, by default PhyloSift is run
       --skip-quast        Skip QUAST analysis, by default QUAST is run
 "
 MORE_HELP="
-The default k-min/max/step parameters are 52/92/8 for IDBA_UD and 21/141/12 for MEGAHIT.
+The default k-min/max/step parameters are 52/92/8 for IDBA_UD and 21/141/12 for
+MEGAHIT.  Unless your under restricted computational resources consider using
+MEGAHIT with 21/255/6 or so, as each additional assembly step will take less
+time than the previous step.  With 64 CPUs this should only take about a day or
+two for moderately large datasets.
+
+Note on normalization:  We use BBNorm to normalize maximum read-depth.  The
+target depth is about 35ish.  To reduce computation time we recommend fast
+access to where the reads are stored and many CPUs and a few hundred GB RAM.
+Set environment variable TMPDIR to a fast local storage with a few 100GB of
+empty space. Expect normalization of 1TB of fastq data to take about a day.
 "
 # shellcheck disable=SC2100
 SHORT_OPTIONS=t:
-LONG_OPTIONS="assembly-only,assembly:,name:,cpus:,force,idba-ud,maxk:,megahit,mink:,level:,out:,phylosiftrc:,reads:,step:,skip-blast,skip-phylosift,skip-quast,threads:"
+LONG_OPTIONS="assembly-only,assembly:,name:,cpus:,force,idba-ud,maxk:,megahit,mink:,normalized-reads:,level:,out:,phylosiftrc:,reads:,step:,skip-blast,skip-normalization,skip-phylosift,skip-quast,threads:"
 }
 
 handle_options () {
@@ -75,6 +90,10 @@ handle_options () {
 	(--mink)
 	    MINK="$2"
 	    return 2;;
+        (--normalized-reads)
+            NORM_READS="$2"
+	    RUN_BBNORM=false
+            return 2;;
 	(--level)
 	    ASSEMBLY_LEVEL="$2"
 	    return 2;;
@@ -92,6 +111,9 @@ handle_options () {
 	    return 2;;
 	(--skip-blast)
 	    RUN_BLAST=false
+	    return 1;;
+	(--skip-normalization)
+	    RUN_BBNORM=false
 	    return 1;;
 	(--skip-phylosift)
 	    RUN_PHYLOSIFT=false
@@ -122,11 +144,14 @@ DEFAULT_CPUS=4
 FORCE=false
 # Use megahit by default, if false, then use idba_ud
 MEGAHIT=true
+#
+NORM_READS=
 # PhyloSift run control file
 PHYLOSIFTRC="$(dirname "$0")/../share/geo-omics-scripts/phylosiftrc"
 # interleaved reads as made by qc script
 READS=int.good.fasta
 #
+RUN_BBNORM=true
 RUN_BLAST=true
 RUN_PHYLOSIFT=true
 RUN_QUAST=true
@@ -222,17 +247,53 @@ if [ -n "$ASSEMBLY" ]; then
     fi
 else
     # check if reads exists before doing anything
-    for i in "${SAMPLE_DIRS[@]}"; do
-        [ -d "$i" ] || abort "is not a directory: $i"
+    reads=("${SAMPLE_DIRS[@]/%//$READS}")
+    for i in "${reads[@]}"; do
+        [ -d "$(dirname "$i")" ] || error "is not a directory: $(dirname "$i")"
         [ -r "$i/$READS" ] || abort "interleaved reads file not found: $i/$READS"
     done
 
-    if [ ${#SAMPLE_DIRS[@]} -gt 1 ]; then
-        reads=("${SAMPLE_DIRS[@]/%//$READS}")
+    # Use comma-separated list of read files for bbnorm and possibly megahit input
+    # This assumes no spaces in file or dir names
+    reads_listed="$(echo "${reads[@]}" | sed -r 's/[ ]+/,/g')"
+
+    if [[ -n "$NORM_READS" ]]; then
+        [[ -e "$NORM_READS" ]] || abort "Normalized reads file not found: $NORM_READS"
+        reads_arg=$NORM_READS
+
+    elif $RUN_BBNORM; then
+        reads_suffix=${READS##*.}
+        norm_reads=$OUTDIR/${READS/%.${reads_suffix}/.norm.${reads_suffix}}
+        if [[ -e "$norm_reads" ]]; then
+            if $FORCE; then
+                info "Removing existing $norm_reads per --force option"
+                rm -- "$norm_reads"
+            else
+                abort "Normalized reads file exists.  Use \"--normalized-reads $norm_reads\" to use this file for assembly or --force to overwrite"
+            fi
+        fi
+
+        # set up temp dir use for vondamm and cayman
+        TMPFAST=/tmp/fast
+        if [[ -z "$TMPDIR" ]] && [[ -f $TMPFAST ]]; then
+            info "Attempting to use $TMPFAST to store BBNorm temporary data"
+            export TMPDIR=$TMPFAST
+        fi
+
+        bbnorm_log=$OUTDIR/bbnorm.log
+        bbnorm_args=(
+            in=$reads_listed
+            out=$norm_reads
+            threads=$CPUS
+            target=30
+        )
+        /usr/bin/time -v bbnorm "${bbnorm_args[@]}" |& tee "$bbnorm_log"
+        reads_arg=$norm_reads
+    else
+
+        # assemble un-normalized reads
         if $MEGAHIT; then
-            # make comma-separated list of read files for megahit
-            # This assumes no spaces in file or dir names
-            reads_arg=$(echo "${reads[@]}" | sed -r 's/ /,/g')
+            reads_arg=$reads_listed
         else
             # idba requires a single read file
             info "Setting up piping of reads into IDBA_UD..."
@@ -240,10 +301,11 @@ else
             mkfifo --mode=600 "$reads_arg"
             cat "${reads[@]}" > "$reads_arg" &
         fi
-    else
+    fi
+
+    if [[ ${#reads[@]} -eq 1 ]]; then
         # descend into single sample directory or working directory, output goes here, too
-        cd "${SAMPLE_DIRS[0]}"
-        reads_arg=$READS
+        cd -- "$(dirname "${reads[0]}")"
     fi
 
     if [ -d "$out" ]; then
